// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBM3JRHlreKsFsYJQtgRtL4KZv2xbh5lk',
    appId: '1:708303731331:web:54dfc6019ea5acce13f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    authDomain: 'meet-d8070.firebaseapp.com',
    storageBucket: 'meet-d8070.firebasestorage.app',
    measurementId: 'G-RP17G4V0JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjYNBs1tKvYVtmJFJin7w3aP803kQEvio',
    appId: '1:708303731331:android:e19d81f7d27ee03e13f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    storageBucket: 'meet-d8070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC105IESZjuxJ4VFj4QytvKv8PiQJffwqM',
    appId: '1:708303731331:ios:c0f67c21c442ef7713f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    storageBucket: 'meet-d8070.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC105IESZjuxJ4VFj4QytvKv8PiQJffwqM',
    appId: '1:708303731331:ios:c0f67c21c442ef7713f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    storageBucket: 'meet-d8070.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBM3JRHlreKsFsYJQtgRtL4KZv2xbh5lk',
    appId: '1:708303731331:web:567b6d6edf72220813f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    authDomain: 'meet-d8070.firebaseapp.com',
    storageBucket: 'meet-d8070.firebasestorage.app',
    measurementId: 'G-8W6S3Y2TSS',
  );
}
